### ISSUE TITLE
Integration test for the all method

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-trail#295]
**Test Scenario 1: Retrieve all licenses for a valid title**
1. Create a new title by calling `title` method with a valid `ptr`, `origin`, `tags`, and `description`.
2. Create two new licenses for the title by calling `license` method with the title's `ptr`, `origin`, `uses`, `terms`, `description`, and `expiry`.
3. Call `all` method with the title's `ptr` and `origin`.
4. Verify that the method returns a list of two `LicenseRecord` objects with correct values for each field.

**Test Scenario 2: Retrieve all licenses for an invalid title**
1. Call `all` method with an invalid `ptr` and a valid `origin`.
2. Verify that the method returns an empty list.

**Test Scenario 3: Retrieve all licenses for a title with no licenses**
1. Create a new title by calling `title` method with a valid `ptr`, `origin`, `tags`, and `description`.
2. Call `all` method with the title's `ptr` and `origin`.
3. Verify that the method returns an empty list.

**Comment by Harshit933** [comment]
Can I work on this?

**Comment by ricardobrg** [comment]
@Harshit933 Assigned!
